// qwik-todo/src/components/Header.tsx
import { component$, useSignal, $, type PropFunction } from '@builder.io/qwik';
import { User } from '../types';
import { Button } from './ui/Button';

// Import our custom icons
import { MenuIcon, BellIcon, SettingsIcon, UserIcon, SunIcon, MoonIcon } from './Icons';

export interface HeaderProps {
  currentUser: User;
  isDarkMode: boolean;
  onToggleDarkMode$: PropFunction<() => void>;
}

export const Header = component$<HeaderProps>((props) => {
  const { currentUser, isDarkMode, onToggleDarkMode$ } = props;

  // Local state
  const isMenuOpen = useSignal(false);
  const isNotificationsOpen = useSignal(false);

  // Handlers
  const handleToggleMenu = $(() => {
    isMenuOpen.value = !isMenuOpen.value;
  });

  const handleToggleNotifications = $(() => {
    isNotificationsOpen.value = !isNotificationsOpen.value;
  });

  const handleToggleDarkMode = $(() => {
    onToggleDarkMode$();
  });

  return (
    <header
      style={{
        backgroundColor: 'var(--primary-background)',
        color: 'var(--primary-foreground)',
        padding: '0 16px',
        height: '64px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        boxShadow: 'var(--shadow-sm)',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center' }}>
        <Button intent="ghost" size="icon" aria-label="Menu">
          <MenuIcon />
        </Button>

        <h1
          style={{
            margin: '0 0 0 16px',
            fontSize: '20px',
            fontWeight: 600,
          }}
        >
          Fast Qwik Todo App
        </h1>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
        <Button
          intent="ghost"
          size="icon"
          onClick$={handleToggleDarkMode}
          aria-label={isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'}
        >
          {isDarkMode ? <SunIcon /> : <MoonIcon />}
        </Button>

        <Button intent="ghost" size="icon" onClick$={handleToggleNotifications} aria-label="Notifications">
          <div style={{ position: 'relative' }}>
            <BellIcon />
            <span
              style={{
                position: 'absolute',
                top: '-5px',
                right: '-5px',
                backgroundColor: 'var(--destructive-background)',
                color: 'var(--destructive-foreground)',
                borderRadius: '50%',
                width: '16px',
                height: '16px',
                fontSize: '10px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              3
            </span>
          </div>
        </Button>

        <Button intent="ghost" size="icon" aria-label="Settings">
          <SettingsIcon />
        </Button>

        <Button intent="ghost" size="icon" onClick$={handleToggleMenu} aria-label="User menu">
          <div style={{ position: 'relative' }}>
            {currentUser.avatar ? (
              <img
                src={currentUser.avatar}
                alt={currentUser.name}
                style={{
                  width: '24px',
                  height: '24px',
                  borderRadius: '50%',
                }}
              />
            ) : (
              <UserIcon />
            )}
          </div>
        </Button>
      </div>

      {isMenuOpen.value && (
        <div
          style={{
            position: 'absolute',
            top: '64px',
            right: '16px',
            backgroundColor: 'var(--card)',
            color: 'var(--card-foreground)',
            borderRadius: 'var(--radius-md)',
            boxShadow: 'var(--shadow-md)',
            minWidth: '200px',
            zIndex: 50,
          }}
        >
          <div style={{ padding: '8px 16px', borderBottom: '1px solid var(--border)' }}>
            <div style={{ fontWeight: 600 }}>{currentUser.name}</div>
            <div style={{ fontSize: '14px', color: 'var(--muted-foreground)' }}>{currentUser.email}</div>
          </div>

          <div style={{ padding: '8px 0' }}>
            <button
              style={{
                display: 'block',
                width: '100%',
                textAlign: 'left',
                padding: '8px 16px',
                backgroundColor: 'transparent',
                border: 'none',
                cursor: 'pointer',
                color: 'var(--foreground)',
                fontSize: '14px',
              }}
            >
              Profile
            </button>

            <button
              style={{
                display: 'block',
                width: '100%',
                textAlign: 'left',
                padding: '8px 16px',
                backgroundColor: 'transparent',
                border: 'none',
                cursor: 'pointer',
                color: 'var(--foreground)',
                fontSize: '14px',
              }}
            >
              Settings
            </button>

            <button
              style={{
                display: 'block',
                width: '100%',
                textAlign: 'left',
                padding: '8px 16px',
                backgroundColor: 'transparent',
                border: 'none',
                cursor: 'pointer',
                color: 'var(--destructive-background)',
                fontSize: '14px',
              }}
            >
              Logout
            </button>
          </div>
        </div>
      )}

      {isNotificationsOpen.value && (
        <div
          style={{
            position: 'absolute',
            top: '64px',
            right: '16px',
            backgroundColor: 'var(--card)',
            color: 'var(--card-foreground)',
            borderRadius: 'var(--radius-md)',
            boxShadow: 'var(--shadow-md)',
            minWidth: '300px',
            zIndex: 50,
          }}
        >
          <div
            style={{
              padding: '12px 16px',
              borderBottom: '1px solid var(--border)',
              fontWeight: 600,
            }}
          >
            Notifications
          </div>

          <div>
            {[
              { id: 1, text: 'New task assigned to you', time: '5 minutes ago' },
              { id: 2, text: 'Task "Complete project report" is due tomorrow', time: '2 hours ago' },
              { id: 3, text: 'Your task "Review design mockups" was updated', time: '1 day ago' },
            ].map((notification) => (
              <div
                key={notification.id}
                style={{
                  padding: '12px 16px',
                  borderBottom: '1px solid var(--border)',
                  cursor: 'pointer',
                }}
              >
                <div>{notification.text}</div>
                <div style={{ fontSize: '12px', color: 'var(--muted-foreground)', marginTop: '4px' }}>
                  {notification.time}
                </div>
              </div>
            ))}
          </div>

          <div
            style={{
              padding: '8px 16px',
              textAlign: 'center',
              fontSize: '14px',
              color: 'var(--primary-background)',
              cursor: 'pointer',
            }}
          >
            Mark all as read
          </div>
        </div>
      )}
    </header>
  );
});

// slow-nextjs-todo/src/app/components/Header.tsx
'use client';

import React, { useState, useEffect } from 'react';
import {
  AppBar,
  Toolbar,
  Typography,
  Box,
  IconButton,
  Avatar,
  Menu,
  MenuItem,
  Divider,
  Tooltip,
  Badge,
  CircularProgress,
} from '@mui/material';
import {
  Notifications as NotificationsIcon,
  Settings as SettingsIcon,
  Brightness4 as DarkModeIcon,
  Brightness7 as LightModeIcon,
  Menu as MenuIcon,
} from '@mui/icons-material';
import { User } from '../types';
import { useThemeMode } from '../theme-registry';

interface HeaderProps {
  currentUser: User;
}

// Header component with unnecessary computations and delays
export default function Header({ currentUser }: HeaderProps) {
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
  const [notificationAnchorEl, setNotificationAnchorEl] = useState<null | HTMLElement>(null);
  const [unreadNotifications, setUnreadNotifications] = useState(3);
  const [isLoading, setIsLoading] = useState(true);

  // Get dark mode from context
  const { darkMode, toggleDarkMode } = useThemeMode();

  // Effect to simulate loading state
  useEffect(() => {
    if (typeof window !== 'undefined') {
      // Remove artificial delay and expensive calculation
      setIsLoading(false);
    }
  }, []);

  const handleProfileClick = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleProfileClose = () => {
    setAnchorEl(null);
  };

  const handleNotificationClick = (event: React.MouseEvent<HTMLElement>) => {
    setNotificationAnchorEl(event.currentTarget);
  };

  const handleNotificationClose = () => {
    setNotificationAnchorEl(null);
    setUnreadNotifications(0);
  };

  const handleToggleDarkMode = () => {
    toggleDarkMode();
  };

  // Dummy notifications
  const notifications = [
    { id: 1, text: 'New task assigned to you', time: '5 minutes ago' },
    { id: 2, text: 'Task "Complete project report" is due tomorrow', time: '2 hours ago' },
    { id: 3, text: 'Your task "Review design mockups" was updated', time: '1 day ago' },
  ];

  if (isLoading) {
    return (
      <AppBar position="static" color="primary">
        <Toolbar>
          <Box sx={{ display: 'flex', alignItems: 'center', width: '100%', justifyContent: 'center', py: 2 }}>
            <CircularProgress color="inherit" size={24} sx={{ mr: 2 }} />
            <Typography variant="h6">Loading...</Typography>
          </Box>
        </Toolbar>
      </AppBar>
    );
  }

  return (
    <AppBar position="static" color="primary">
      <Toolbar>
        <IconButton edge="start" color="inherit" aria-label="menu" sx={{ mr: 2 }}>
          <MenuIcon />
        </IconButton>

        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
          Slow NextJS Todo App
        </Typography>

        <Box sx={{ display: 'flex', alignItems: 'center' }}>
          <Tooltip title={darkMode ? 'Switch to Light Mode' : 'Switch to Dark Mode'}>
            <IconButton color="inherit" onClick={handleToggleDarkMode}>
              {darkMode ? <LightModeIcon /> : <DarkModeIcon />}
            </IconButton>
          </Tooltip>

          <Tooltip title="Notifications">
            <IconButton
              color="inherit"
              onClick={handleNotificationClick}
              aria-controls={notificationAnchorEl ? 'notification-menu' : undefined}
              aria-haspopup="true"
              aria-expanded={notificationAnchorEl ? 'true' : undefined}
            >
              <Badge badgeContent={unreadNotifications} color="error">
                <NotificationsIcon />
              </Badge>
            </IconButton>
          </Tooltip>

          <Menu
            id="notification-menu"
            anchorEl={notificationAnchorEl}
            open={Boolean(notificationAnchorEl)}
            onClose={handleNotificationClose}
            MenuListProps={{
              'aria-labelledby': 'notification-button',
            }}
            sx={{ mt: 2 }}
          >
            <Box sx={{ p: 2, minWidth: '300px' }}>
              <Typography variant="subtitle1" fontWeight="bold">
                Notifications
              </Typography>
            </Box>
            <Divider />
            {notifications.map((notification) => (
              <MenuItem key={notification.id} onClick={handleNotificationClose}>
                <Box sx={{ display: 'flex', flexDirection: 'column', py: 1 }}>
                  <Typography variant="body1">{notification.text}</Typography>
                  <Typography variant="caption" color="text.secondary">
                    {notification.time}
                  </Typography>
                </Box>
              </MenuItem>
            ))}
            <Divider />
            <MenuItem onClick={handleNotificationClose}>
              <Typography variant="body2" sx={{ width: '100%', textAlign: 'center' }}>
                Mark all as read
              </Typography>
            </MenuItem>
          </Menu>

          <Tooltip title="Settings">
            <IconButton color="inherit">
              <SettingsIcon />
            </IconButton>
          </Tooltip>

          <Tooltip title={currentUser.name}>
            <IconButton
              onClick={handleProfileClick}
              aria-controls={anchorEl ? 'profile-menu' : undefined}
              aria-haspopup="true"
              aria-expanded={anchorEl ? 'true' : undefined}
              color="inherit"
              sx={{ ml: 1 }}
            >
              <Avatar alt={currentUser.name} src={currentUser.avatar} sx={{ width: 32, height: 32 }} />
            </IconButton>
          </Tooltip>

          <Menu
            id="profile-menu"
            anchorEl={anchorEl}
            open={Boolean(anchorEl)}
            onClose={handleProfileClose}
            MenuListProps={{
              'aria-labelledby': 'profile-button',
            }}
            sx={{ mt: 2 }}
          >
            <MenuItem onClick={handleProfileClose}>Profile</MenuItem>
            <MenuItem onClick={handleProfileClose}>My account</MenuItem>
            <Divider />
            <MenuItem onClick={handleProfileClose}>Logout</MenuItem>
          </Menu>
        </Box>
      </Toolbar>
    </AppBar>
  );
}
